export default {
  success: true,
  properties: [
    {
      id: "1",
      address: "karachi",
      postcode: "22303",
      rooms: "4",
      type: "Flat",
      area: "63",
    },
    {
      id: "2",
      address: "sahiwal",
      postcode: "21305",
      rooms: "4",
      type: "Terraced",
      area: "70",
    },
    {
      id: "3",
      address: "lahore",
      postcode: "24530",
      rooms: "4",
      type: "Semi-detached",
      area: "56",
    },
    {
      id: "4",
      address: "Muzaffarabad",
      postcode: "24530",
      rooms: "4",
      type: "Flat",
      area: "56",
    },
    {
      id: "5",
      address: "Rawalpindi",
      postcode: "24530",
      rooms: "4",
      type: "Terraced",
      area: "56",
    },
    {
      id: "6",
      address: "Sialkot",
      postcode: "24530",
      rooms: "4",
      type: "Flat",
      area: "56",
    },
    {
      id: "7",
      address: "Multan",
      postcode: "24530",
      rooms: "4",
      type: "Semi-detached",
      area: "56",
    },
    {
      id: "8",
      address: "Hydrabad",
      postcode: "24530",
      rooms: "4",
      type: "Terraced",
      area: "56",
    },
    {
      id: "9",
      address: "Sargodha",
      postcode: "24530",
      rooms: "4",
      type: "Semi-detached",
      area: "56",
    },
    {
      id: "10",
      address: "Islamabad",
      postcode: "24530",
      rooms: "4",
      type: "Flat",
      area: "56",
    },
  ],
};
